const rawOutputQuestions = [
  {
    id: "hoist-var",
    type: "output",
    topic: "Hoisting",
    title: "var and undefined",
    prompt: "What does this code log?",
    code: "console.log(a);\nvar a = 5;",
    expected: "undefined",
    explanation:
      "HOISTING PHASE (before execution):\n1. JavaScript engine scans the code and 'hoists' var a → creates a binding with value undefined\n2. The assignment (a = 5) stays in place\n\nEXECUTION PHASE:\n1. console.log(a) runs → var a exists but is still undefined\n2. Then a = 5 is executed\n\n📌 KEY: var declarations are split — the declaration is hoisted and set to undefined, but the assignment stays at its original line.",
    options: ["5", "undefined", "null", "ReferenceError"],
  },
  {
    id: "tdz-let",
    type: "output",
    topic: "TDZ",
    title: "let before declaration",
    prompt: "What happens here?",
    code: "console.log(a);\nlet a = 5;",
    expected: "ReferenceError",
    explanation:
      "HOISTING PHASE:\n1. let a is hoisted BUT placed in 'Temporal Dead Zone' (TDZ)\n2. let bindings are NOT initialized to undefined (unlike var)\n\nEXECUTION PHASE:\n1. console.log(a) tries to access 'a' while it's in TDZ\n2. ReferenceError is thrown: 'Cannot access 'a' before initialization'\n3. Code stops here\n\n📌 KEY: let/const are 'hoisted' but unusable until their declaration line is reached. They stay in TDZ from scope start to declaration.",
    options: ["undefined", "5", "null", "ReferenceError"],
  },
  {
    id: "fn-hoist",
    type: "output",
    topic: "Functions",
    title: "function declarations",
    prompt: "What gets printed?",
    code: 'foo();\nfunction foo() {\n  console.log("Hello");\n}',
    expected: "Hello",
    explanation:
      "HOISTING PHASE (before any code runs):\n1. Function declarations are FULLY hoisted with their complete body\n2. foo() is available in memory with its full implementation\n\nEXECUTION PHASE:\n1. foo() is called — it's already there\n2.'Hello' is logged\n\n📌 KEY: Function declarations are special — the ENTIRE function (not just the name) is hoisted. You can call it before it appears in code.",
    options: ["Hello", "undefined", "ReferenceError", "TypeError"],
  },
  {
    id: "fn-expr-var",
    type: "output",
    topic: "Functions",
    title: "function expression on var",
    prompt: "What happens when foo is called?",
    code: 'foo();\nvar foo = function() {\n  console.log("Hello");\n};',
    expected: "TypeError",
    explanation:
      "HOISTING PHASE:\n1. var foo is hoisted and initialized to undefined\n2. The function body is NOT hoisted (it's an expression, not a declaration)\n\nEXECUTION PHASE:\n1. foo() tries to call foo\n2. But foo is currently undefined\n3. TypeError: foo is not a function ❌\n\n📌 KEY: Function expressions are different from declarations. Only the var binding is hoisted (as undefined), not the function itself.",
    options: ["Hello", "undefined", "ReferenceError", "TypeError"],
  },
  {
    id: "multi-var",
    type: "output",
    topic: "Hoisting",
    title: "multiple var assignments",
    prompt: "What are the two logs?",
    code: "console.log(a);\nvar a = 1;\nvar a = 2;\nconsole.log(a);",
    expected: "undefined\n2",
    explanation:
      'HOISTING PHASE:\n1. var a appears twice, but hoisting only creates ONE binding\n2. a is initialized to undefined\n\nEXECUTION PHASE:\n1. console.log(a) → a is undefined → logs "undefined"\n2. a = 1 → a is now 1\n3. a = 2 → a is now 2 (overwrites previous)\n4. console.log(a) → a is 2 → logs "2"\n\n📌 KEY: Multiple var declarations of the same name don\'t create multiple bindings. Only one binding exists, and assignments overwrite the previous value.',
    options: ["undefined, 2", "1, 2", "undefined, 1", "1, 1"],
  },
  {
    id: "loop-var-timeout",
    type: "output",
    topic: "Closures",
    title: "var in a loop",
    prompt: "What do the timeouts print?",
    code: "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
    expected: "3\n3\n3",
    explanation:
      "SCOPE ISSUE:\n1. var i is FUNCTION-SCOPED (not block-scoped)\n2. The var i hoisting brings it to the function level — only ONE i binding\n\nEXECUTION PHASE:\n1. Loop runs: i=0, i=1, i=2\n2. Each iteration schedules a callback with setTimeout\n3. Loop finishes: i=3 (from i++ when condition became false)\n4. Callbacks execute: they all close over the SAME i binding\n5. i is now 3, so all callbacks log 3\n\n📌 KEY: var is function-scoped. All callbacks share ONE i binding. By the time they run asynchronously, i has already reached 3.",
    options: [
      "0\n1\n2",
      "3\n3\n3",
      "undefined\nundefined\nundefined",
      "0\n0\n0",
    ],
  },
  {
    id: "loop-let-timeout",
    type: "output",
    topic: "Closures",
    title: "let in a loop",
    prompt: "What do the timeouts print?",
    code: "for (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
    expected: "0\n1\n2",
    explanation:
      "SCOPE DIFFERENCE:\n1. let i is BLOCK-SCOPED\n2. JavaScript creates a NEW binding for each iteration\n3. Each callback captures its OWN i value\n\nEXECUTION PHASE:\n1. Iteration 0: new i binding = 0, callback scheduled → captures i=0\n2. Iteration 1: new i binding = 1, callback scheduled → captures i=1\n3. Iteration 2: new i binding = 2, callback scheduled → captures i=2\n4. Callbacks execute: each has its own i value\n5. Logs: 0, 1, 2\n\n📌 KEY: let creates a per-iteration binding. Each callback closes over its own i. This is the major difference between var and let in loops.",
    options: [
      "0\n1\n2",
      "3\n3\n3",
      "undefined\nundefined\nundefined",
      "0\n0\n0",
    ],
  },
  {
    id: "function-scope-var",
    type: "output",
    topic: "Scope",
    title: "function scope hoisting",
    prompt: "What is logged?",
    code: "function test() {\n  console.log(a);\n  var a = 10;\n}\ntest();",
    expected: "undefined",
    explanation:
      'HOISTING PHASE:\n1. Function test is hoisted (fully)\n2. Inside test, var a is hoisted to the TOP of the function\n\nEXECUTION PHASE:\n1. test() is called\n2. Inside test, console.log(a) runs\n3. a exists (hoisted) but is undefined\n4. Logs "undefined"\n5. Then a = 10 is executed\n\n📌 KEY: Hoisting happens at FUNCTION SCOPE. Variables are hoisted to the top of their containing function, not the global scope.',
    options: ["10", "undefined", "ReferenceError", "null"],
  },
  {
    id: "shadowed-var",
    type: "output",
    topic: "Scope",
    title: "shadowed var",
    prompt: "What is logged?",
    code: "var x = 10;\nfunction foo() {\n  console.log(x);\n  var x = 20;\n}\nfoo();\nconsole.log(x);",
    expected: "undefined\n10",
    explanation:
      'HOISTING PHASE:\n1. Global var x = 10 is hoisted\n2. Inside foo, a LOCAL var x is also hoisted (shadows global x)\n\nEXECUTION PHASE:\n1. foo() is called\n2. console.log(x) looks for x: finds the LOCAL x (hoisted, undefined)\n3. Logs "undefined"\n4. x = 20 assigns to the local x\n5. Function ends\n6. console.log(x) looks for x: finds the GLOBAL x (still 10)\n7. Logs "10"\n\n📌 KEY: Local scope shadows outer scope. The function\'s own hoisted var x blocks access to the global x until inside the function scope.',
    options: ["10\n10", "undefined\n10", "20\n20", "undefined\nundefined"],
  },
  {
    id: "inner-shadow",
    type: "output",
    topic: "Scope",
    title: "nested scope shadowing",
    prompt: "What is logged by inner?",
    code: "function outer() {\n  var a = 10;\n  function inner() {\n    console.log(a);\n    var a = 20;\n  }\n  inner();\n}\nouter();",
    expected: "undefined",
    explanation:
      "HOISTING PHASE:\n1. outer and inner are hoisted as full functions\n2. Inside inner, var a is hoisted to the top of inner's scope\n\nEXECUTION PHASE:\n1. outer() is called\n2. var a = 10 is executed (outer's a)\n3. inner() is called\n4. console.log(a) inside inner: finds the LOCAL a (hoisted, undefined)\n5. Logs \"undefined\"\n6. a = 20 assigns to locally scoped a\n\n📌 KEY: Even though outer has a = 10, inner's local var a shadows it completely. The local undefined binding wins.",
    options: ["10", "20", "undefined", "ReferenceError"],
  },
  {
    id: "function-before-var",
    type: "output",
    topic: "Hoisting",
    title: "function beats var initially",
    prompt: "What are the logs?",
    code: "console.log(foo);\nfunction foo() {}\nvar foo = 10;\nconsole.log(foo);",
    expected: "[Function: foo]\n10",
    explanation:
      'HOISTING PHASE:\n1. function foo() {} is fully hoisted — foo becomes a function object\n2. var foo is hoisted, but foo is already a function, so the declaration is ignored\n\nEXECUTION PHASE:\n1. console.log(foo) → foo is the function object → logs "[Function: foo]"\n2. foo = 10 → ASSIGNMENT overwrites foo with the number 10\n3. console.log(foo) → foo is now 10 → logs "10"\n\n📌 KEY: Functions are hoisted BEFORE var declarations. Assignments always overwrite any previous binding.',
    options: [
      "undefined, 10",
      "[Function: foo], 10",
      "[Function: foo], [Function: foo]",
      "10, 10",
    ],
  },
  {
    id: "var-overwrites-function",
    type: "output",
    topic: "Hoisting",
    title: "var overwrites function value",
    prompt: "What is logged?",
    code: "var foo = 10;\nfunction foo() { return 20; }\nconsole.log(foo);",
    expected: "10",
    explanation:
      'HOISTING PHASE:\n1. function foo() {} is fully hoisted\n2. var foo is hoisted (but foo already exists, so ignored)\n\nEXECUTION PHASE:\n1. foo = 10 → ASSIGNMENT happens, overwrites the function\n2. console.log(foo) → foo is 10 → logs "10"\n\n📌 KEY: Hoisting order matters! Functions are hoisted first, but runtime assignments always win. foo ends up as 10, not the function.',
    options: ["10", "20", "[Function: foo]", "undefined"],
  },
];

export const outputQuestions = rawOutputQuestions.map((question) => ({
  ...question,
  type: "output",
}));
